# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: node:16.17.0

pipelines:
  branches:
    master:
      - step:
          name: 빌드 & env 파일 설정
          artifacts:
            - .next/**
            - .env.production
            - node_modules/**
            - public/**
          script:
            - touch .env.production
            - echo NEXT_PUBLIC_ENDPOINT=${API_ENDPOINT} >> .env.production
            - npm install
            - npm run build
      - parallel:
          - step:
              name: ServerIP-Port Deploy
              script:
                - pipe: atlassian/rsync-deploy:0.8.1
                  variables:
                    USER: $USER
                    SERVER: $SERVER1
                    REMOTE_PATH: $PROJECT_PATH
                    LOCAL_PATH: "${BITBUCKET_CLONE_DIR}/"

      - parallel:
          - step:
              name: use shell script
              script:
                - pipe: atlassian/ssh-run:0.4.1
                  variables:
                    SSH_USER: $USER
                    SERVER: $SERVER1
                    COMMAND: $SH_PATH/exec.sh

definitions:
  caches:
    nextcache: .next/cache
